### ISSUE TITLE
Unity SDK causes issues with scriptable build pipeline on StandaloneOSX

### ISSUE THREAD

**Issue by halawa** [ByteBrewIO/ByteBrewUnitySDK#1]
I'm on SDK version 0.0.7.

When my target is set to Standalone, the SDK causes the errors shown below when I try to build asset bundles.

`Assets/ByteBrewSDK/Scripts/ByteBrew.cs(569,30): error CS0161: 'ByteBrew.GetRemoteConfigForKey(string, string)': not all code paths return a value`

`Assets/ByteBrewSDK/Scripts/ByteBrew.cs(585,28): error CS0161: 'ByteBrew.HasRemoteConfigsBeenSet()': not all code paths return a value`

`Assets/ByteBrewSDK/Scripts/ByteBrew.cs(601,30): error CS0161: 'ByteBrew.GetUserID()': not all code paths return a value`

The way I've seen it in other SDKs is that they fallback to some dummy behaviors when the target is not Android or iOS.

**Comment by ByteBrewIO** [comment]
Hi, ByteBrew currently only supports mobile platforms. A quick fix you could do right now to resolve the issue is to add a Defining `#else` block to the end of the returning methods so for any other platforms it will return blank variables.
Go into the `ByteBrew.cs` file and Locate the three methods where this error is occurring and add the platform definitions after the last `#elif`.
Like so:
`#else 
   return "";  
#endif `

We made a note to resolve this issue in one of our upcoming release of the SDK.
