### ISSUE TITLE
IsByteBrewInitialized() always return false on iOS if ATT status is not authorized

### ISSUE THREAD

**Issue by tyrng** [ByteBrewIO/ByteBrewUnitySDK#3]
On latest version after I initialized ByteBrew on iOS with the provided ATT wrapper, if user does not allow ATT, IsByteBrewInitialized() will always return false. As my application checks for IsByteBrewInitialized() before other initialization steps, this has been a blocker for us.

So I tried another approach: If I ignore IsByteBrewInitialized() or I don't initialize ByteBrew when user does not allow ATT, purchase validation callback will not be called instead.

Is there any way for us to use ByteBrew when ATT is not authorized?

**Comment by cameronhozouri** [comment]
Hi @tyrng ,
ByteBrew SDK does not require ATT to be initialized. At first glance this looks like it could be an issue with the way you're initializing. We'd be happy to help find where the issue is located. Please send us a message at [contact@bytebrew.io](mailto:contact@bytebrew.io) to speak with our team to get this sorted.
